### ISSUE TITLE
debug vercel serverless api like function~

### ISSUE THREAD

**Issue by scarqin** [killdada/you-can-form-render#2]
https://www.youtube.com/watch?v=giEL-ZLE6C4
![](https://user-images.githubusercontent.com/15225835/171024173-c2830adf-3ccf-47f4-a345-7b881863121f.png)
![](https://user-images.githubusercontent.com/15225835/171024216-430d3c0e-b9e1-4262-8b40-396078c992f1.png)

**Comment by scarqin** [comment]
https://github.com/vercel/vercel/discussions/4634
try to configure the port

**Comment by killdada** [comment]
> [vercel/vercel#4634](https://github.com/vercel/vercel/discussions/4634) try to configure the port

试着加 port一直还是 有问题，然后clone官网的umi项目后验证官网的demo可以本地调试，然后把本地的client目录全部迁移到了这个clone的项目后本地跑正常调试了，可能跟根目录有关？还是类型必须选umi？

**Comment by killdada** [comment]
> [vercel/vercel#4634](https://github.com/vercel/vercel/discussions/4634) try to configure the port

刚验证了，是 应用类型必须选 umi ，不然会有问题，我去看看其他类型对应，后续如果midway egg是选什么

**Comment by scarqin** [comment]
恭喜～
